Repository trendmicro/cloudone-community, pull requests merged in 2022-06, with the labels that each got.

#13 Implement quality updates to the repository 📊
  .github/workflows/codeql.yml
  .github/workflows/group-mover-linter.yml
  .github/workflows/linter.yml
  LICENSE
  README.md
  Workload-Security/Migration/bash-group-mover/README.md
Labels: Documentation :book:, Enhancement :sparkles:

#15 feat: fssdeployment script
  File-Storage-Security/Deployment/python-deploy-to-all-existing-s3/README.md
  File-Storage-Security/Deployment/python-deploy-to-all-existing-s3/deploy.py
  File-Storage-Security/Deployment/python-deploy-to-all-existing-s3/exclude.txt
  File-Storage-Security/Deployment/python-deploy-to-all-existing-s3/requirements.txt
Labels: New Project :tada:

#19 Add javascript support to CodeQL and fix linter misconfiguration
  .github/workflows/codeql.yml
  .github/workflows/linter.yml
Labels: Bug :beetle:, Enhancement :sparkles:

#20 Remove cfn-lint from super-linter and add a dedicated step for cfn-lint
  .github/workflows/linter.yml
Labels: Bug :beetle:, Enhancement :sparkles:
