Repository trendmicro/cloudone-community, pull requests merged in 2022-08, with the labels that each got.

#24 Replacing solutions-architect to cloudone-community
  .github/CONTRIBUTING.md
  File-Storage-Security/Deployment/python-deploy-to-all-existing-s3/README.md
  README.md
  Workload-Security/Migration/bash-group-mover/README.md
Labels: Documentation :book:, Enhancement :sparkles:, Bug-Fix :syringe:

#27 change name from ds to c1 workload security on Workload-Security/Deployment/python-agent-deploy-automation-using-lambda/
  Workload-Security/Deployment/python-agent-deploy-automation-using-lambda/Architecture_version2.png
  Workload-Security/Deployment/python-agent-deploy-automation-using-lambda/CloudFormation/CFAutomationDSADeploy.template
  Workload-Security/Deployment/python-agent-deploy-automation-using-lambda/README.md
Labels: Enhancement :sparkles:

#26 add well-architected-review-tool
  Conformity/Integration/aws-well-architected-review-tool/.gitignore
  Conformity/Integration/aws-well-architected-review-tool/IAM/outputs.tf
  Conformity/Integration/aws-well-architected-review-tool/IAM/providers.tf
  Conformity/Integration/aws-well-architected-review-tool/IAM/setup-iam.tf
  Conformity/Integration/aws-well-architected-review-tool/IAM/variables.tf
  Conformity/Integration/aws-well-architected-review-tool/LICENSE
  Conformity/Integration/aws-well-architected-review-tool/README.md
Labels: New Project :tada:

#28 Conformity-to-S3 project migration from @raphabot
  Conformity/Integration/aws-cdk-conformity-to-s3/.gitignore
  Conformity/Integration/aws-cdk-conformity-to-s3/.npmignore
  Conformity/Integration/aws-cdk-conformity-to-s3/README.md
  Conformity/Integration/aws-cdk-conformity-to-s3/bin/conformity-to-s3.ts
  Conformity/Integration/aws-cdk-conformity-to-s3/cdk.json
  Conformity/Integration/aws-cdk-conformity-to-s3/jest.config.js
  Conformity/Integration/aws-cdk-conformity-to-s3/lib/conformity-to-s3-stack.ts
  Conformity/Integration/aws-cdk-conformity-to-s3/package-lock.json
  Conformity/Integration/aws-cdk-conformity-to-s3/package.json
  Conformity/Integration/aws-cdk-conformity-to-s3/test/conformity-to-s3.test.ts
  Conformity/Integration/aws-cdk-conformity-to-s3/tsconfig.json
Labels: New Project :tada:, Project Migration :recycle:

#29 Workload Security IAM CDK Stack - project migration from @raphabot
  Workload-Security/Integration/aws-cdk-workload-iam-stack/.gitignore
  Workload-Security/Integration/aws-cdk-workload-iam-stack/.npmignore
  Workload-Security/Integration/aws-cdk-workload-iam-stack/README.md
  Workload-Security/Integration/aws-cdk-workload-iam-stack/bin/cloud-one-workload-security-iam.ts
  Workload-Security/Integration/aws-cdk-workload-iam-stack/cdk.json
  Workload-Security/Integration/aws-cdk-workload-iam-stack/jest.config.js
  Workload-Security/Integration/aws-cdk-workload-iam-stack/lib/cloud-one-workload-security-iam-stack.ts
  Workload-Security/Integration/aws-cdk-workload-iam-stack/package-lock.json
  Workload-Security/Integration/aws-cdk-workload-iam-stack/package.json
  Workload-Security/Integration/aws-cdk-workload-iam-stack/tsconfig.json
Labels: New Project :tada:, Project Migration :recycle:

#31 Add AWS integration via Terraform ❤️
  Common/Cloud-Account/aws-tf-cloud-account-connector/IAM/aws-iam-setup.tf
  Common/Cloud-Account/aws-tf-cloud-account-connector/IAM/outputs.tf
  Common/Cloud-Account/aws-tf-cloud-account-connector/IAM/providers.tf
  Common/Cloud-Account/aws-tf-cloud-account-connector/IAM/variables.tf
  Common/Cloud-Account/aws-tf-cloud-account-connector/LICENSE
  Common/Cloud-Account/aws-tf-cloud-account-connector/README.md
Labels: New Project :tada:

#30 Add C1NS AWS account integration
  Network-Security/Integration/aws-tf-c1ns-cloud-account-connector/IAM/c1ns.tf
  Network-Security/Integration/aws-tf-c1ns-cloud-account-connector/IAM/ns_iam_setup.tf
  Network-Security/Integration/aws-tf-c1ns-cloud-account-connector/IAM/outputs.tf
  Network-Security/Integration/aws-tf-c1ns-cloud-account-connector/IAM/providers.tf
  Network-Security/Integration/aws-tf-c1ns-cloud-account-connector/IAM/variables.tf
  Network-Security/Integration/aws-tf-c1ns-cloud-account-connector/LICENSE
  Network-Security/Integration/aws-tf-c1ns-cloud-account-connector/README.md
Labels: New Project :tada:

#33 Fix projects names and quality updates to the README
  Common/Integration/aws-cdk-securityhub-integration/.gitignore
  Common/Integration/aws-cdk-securityhub-integration/.npmignore
  Common/Integration/aws-cdk-securityhub-integration/README.md
  Common/Integration/aws-cdk-securityhub-integration/bin/security-hub.ts
  Common/Integration/aws-cdk-securityhub-integration/cdk.json
  Common/Integration/aws-cdk-securityhub-integration/dist/cloud-one-integrations-security-hub.template.yaml
  Common/Integration/aws-cdk-securityhub-integration/jest.config.js
  Common/Integration/aws-cdk-securityhub-integration/lib/security-hub-stack.ts
  Common/Integration/aws-cdk-securityhub-integration/package-lock.json
  Common/Integration/aws-cdk-securityhub-integration/package.json
  Common/Integration/aws-cdk-securityhub-integration/test/security-hub.test.ts
  Common/Integration/aws-cdk-securityhub-integration/tsconfig.json
  Conformity/Integration/aws-tf-well-architected-review-tool/.gitignore
  Conformity/Integration/aws-tf-well-architected-review-tool/IAM/outputs.tf
  Conformity/Integration/aws-tf-well-architected-review-tool/IAM/providers.tf
  Conformity/Integration/aws-tf-well-architected-review-tool/IAM/setup-iam.tf
  Conformity/Integration/aws-tf-well-architected-review-tool/IAM/variables.tf
  Conformity/Integration/aws-tf-well-architected-review-tool/LICENSE
  Conformity/Integration/aws-tf-well-architected-review-tool/README.md
  File-Storage-Security/Deployment/aws-cf-nested-aio-promote-quarantine-plugin/README.md
  File-Storage-Security/Deployment/aws-cf-nested-aio-promote-quarantine-plugin/aws-aio-nested-w-plugin.yaml
  File-Storage-Security/Deployment/aws-python-deploy-to-all-existing-s3/README.md
  File-Storage-Security/Deployment/aws-python-deploy-to-all-existing-s3/deploy.py
  File-Storage-Security/Deployment/aws-python-deploy-to-all-existing-s3/exclude.txt
  File-Storage-Security/Deployment/aws-python-deploy-to-all-existing-s3/requirements.txt
  README.md
  Workload-Security/Deployment/aws-python-agent-deploy-automation-using-lambda/Architecture_version2.png
  Workload-Security/Deployment/aws-python-agent-deploy-automation-using-lambda/CloudFormation/CFAutomationDSADeploy.template
  Workload-Security/Deployment/aws-python-agent-deploy-automation-using-lambda/Lambda_Function/lambda_function.py
  Workload-Security/Deployment/aws-python-agent-deploy-automation-using-lambda/README.md
  Workload-Security/Deployment/aws-python-agent-deploy-automation-using-lambda/SSM Documents/Install_and_Activation_Document.ssm
Labels: Documentation :book:, Enhancement :sparkles:, Bug-Fix :syringe:
