Repository trendmicro/cloudone-community, pull requests merged in 2023-03, with the labels that each got.

#80 chore: add pipeline to sync to S3
  .github/workflows/pipeline.yaml
Labels: Enhancement :sparkles:, AWS :cloud:

#65 chore: Update the PR template
  .github/pull_request_template.md
Labels: Documentation :book:, Enhancement :sparkles:

#77 feat: SSM with Orgs
  Workload-Security/Deployment/ssm/aws-orgs/c1ws-ssm-orgs.template.yaml
  Workload-Security/Deployment/ssm/aws-orgs/org-img.jpg
  Workload-Security/Deployment/ssm/aws-orgs/readme.md
Labels: enhancement :sparkles:, aws :cloud:

#74 chore: report security vulnerabilities
  SECURITY.md
Labels: documentation :book:, enhancement :sparkles:, ideas :bulb:

#87 chore: Update on-pr.yaml
  .github/workflows/on-pr.yaml
Labels: bug-fix :syringe:

#86 feat: C1NS policy update cves from s3
  Network-Security/Integration/aws-python-amazon-S3-CVEs-integration/README.md
  Network-Security/Integration/aws-python-amazon-S3-CVEs-integration/python:lambda/c1ns-policy-update-s3-cves.py
  Network-Security/Integration/aws-python-amazon-S3-CVEs-integration/python:lambda/custom-event-creation.py
  Network-Security/Integration/aws-python-amazon-S3-CVEs-integration/templates/c1ns-policy-update-s3-cve-template.yaml
Labels: new-project :tada:, aws :cloud:

#88 feat: c1ns policy update cves from s3
  Network-Security/Integration/aws-python-amazon-S3-CVEs-integration/README.md
  Network-Security/Integration/aws-python-amazon-S3-CVEs-integration/templates/c1ns-policy-update-s3-cve-template.yaml
Labels: bug-fix :syringe:, aws :cloud:
